# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dsc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dsc.proto',
  package='dsc',
  syntax='proto3',
  serialized_options=b'\n\006io.dscB\003DSCP\001\242\002\003DSC',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tdsc.proto\x12\x03\x64sc\"\r\n\x0bhumidityMsg\"\t\n\x07tempMsg\"\r\n\x0bpressureMsg\"!\n\rhumidityReply\x12\x10\n\x08humidity\x18\x01 \x01(\x02\"\x19\n\ttempReply\x12\x0c\n\x04temp\x18\x01 \x01(\x02\"!\n\rpressureReply\x12\x10\n\x08pressure\x18\x01 \x01(\x02\x32\x95\x01\n\x03\x44sc\x12\x32\n\x08Humidity\x12\x10.dsc.humidityMsg\x1a\x12.dsc.humidityReply\"\x00\x12&\n\x04Temp\x12\x0c.dsc.tempMsg\x1a\x0e.dsc.tempReply\"\x00\x12\x32\n\x08Pressure\x12\x10.dsc.pressureMsg\x1a\x12.dsc.pressureReply\"\x00\x42\x15\n\x06io.dscB\x03\x44SCP\x01\xa2\x02\x03\x44SCb\x06proto3'
)




_HUMIDITYMSG = _descriptor.Descriptor(
  name='humidityMsg',
  full_name='dsc.humidityMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=31,
)


_TEMPMSG = _descriptor.Descriptor(
  name='tempMsg',
  full_name='dsc.tempMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=42,
)


_PRESSUREMSG = _descriptor.Descriptor(
  name='pressureMsg',
  full_name='dsc.pressureMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=57,
)


_HUMIDITYREPLY = _descriptor.Descriptor(
  name='humidityReply',
  full_name='dsc.humidityReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='humidity', full_name='dsc.humidityReply.humidity', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=92,
)


_TEMPREPLY = _descriptor.Descriptor(
  name='tempReply',
  full_name='dsc.tempReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temp', full_name='dsc.tempReply.temp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=119,
)


_PRESSUREREPLY = _descriptor.Descriptor(
  name='pressureReply',
  full_name='dsc.pressureReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pressure', full_name='dsc.pressureReply.pressure', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['humidityMsg'] = _HUMIDITYMSG
DESCRIPTOR.message_types_by_name['tempMsg'] = _TEMPMSG
DESCRIPTOR.message_types_by_name['pressureMsg'] = _PRESSUREMSG
DESCRIPTOR.message_types_by_name['humidityReply'] = _HUMIDITYREPLY
DESCRIPTOR.message_types_by_name['tempReply'] = _TEMPREPLY
DESCRIPTOR.message_types_by_name['pressureReply'] = _PRESSUREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

humidityMsg = _reflection.GeneratedProtocolMessageType('humidityMsg', (_message.Message,), {
  'DESCRIPTOR' : _HUMIDITYMSG,
  '__module__' : 'dsc_pb2'
  # @@protoc_insertion_point(class_scope:dsc.humidityMsg)
  })
_sym_db.RegisterMessage(humidityMsg)

tempMsg = _reflection.GeneratedProtocolMessageType('tempMsg', (_message.Message,), {
  'DESCRIPTOR' : _TEMPMSG,
  '__module__' : 'dsc_pb2'
  # @@protoc_insertion_point(class_scope:dsc.tempMsg)
  })
_sym_db.RegisterMessage(tempMsg)

pressureMsg = _reflection.GeneratedProtocolMessageType('pressureMsg', (_message.Message,), {
  'DESCRIPTOR' : _PRESSUREMSG,
  '__module__' : 'dsc_pb2'
  # @@protoc_insertion_point(class_scope:dsc.pressureMsg)
  })
_sym_db.RegisterMessage(pressureMsg)

humidityReply = _reflection.GeneratedProtocolMessageType('humidityReply', (_message.Message,), {
  'DESCRIPTOR' : _HUMIDITYREPLY,
  '__module__' : 'dsc_pb2'
  # @@protoc_insertion_point(class_scope:dsc.humidityReply)
  })
_sym_db.RegisterMessage(humidityReply)

tempReply = _reflection.GeneratedProtocolMessageType('tempReply', (_message.Message,), {
  'DESCRIPTOR' : _TEMPREPLY,
  '__module__' : 'dsc_pb2'
  # @@protoc_insertion_point(class_scope:dsc.tempReply)
  })
_sym_db.RegisterMessage(tempReply)

pressureReply = _reflection.GeneratedProtocolMessageType('pressureReply', (_message.Message,), {
  'DESCRIPTOR' : _PRESSUREREPLY,
  '__module__' : 'dsc_pb2'
  # @@protoc_insertion_point(class_scope:dsc.pressureReply)
  })
_sym_db.RegisterMessage(pressureReply)


DESCRIPTOR._options = None

_DSC = _descriptor.ServiceDescriptor(
  name='Dsc',
  full_name='dsc.Dsc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=157,
  serialized_end=306,
  methods=[
  _descriptor.MethodDescriptor(
    name='Humidity',
    full_name='dsc.Dsc.Humidity',
    index=0,
    containing_service=None,
    input_type=_HUMIDITYMSG,
    output_type=_HUMIDITYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Temp',
    full_name='dsc.Dsc.Temp',
    index=1,
    containing_service=None,
    input_type=_TEMPMSG,
    output_type=_TEMPREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Pressure',
    full_name='dsc.Dsc.Pressure',
    index=2,
    containing_service=None,
    input_type=_PRESSUREMSG,
    output_type=_PRESSUREREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DSC)

DESCRIPTOR.services_by_name['Dsc'] = _DSC

# @@protoc_insertion_point(module_scope)
