FROM python:3.9-alpine

RUN apk update && apk upgrade

RUN apk add --update --no-cache \
    gcc \
    bash \
    linux-headers \
    python3-dev \
    g++

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install -r requirements.txt

