apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs
spec:
  selector:
    matchLabels:
      app: logs
  replicas: 1
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
      - name: python-logs
        image: aliaoco/lab7-logs:latest
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: RABBITMQ_HOST
          value: rabbitmq
        